### PR TITLE
Update ido recomp binaries

### PR DESCRIPTION
**Pull request by hensldm**
Updates the ido recomp binaries.
1. Fixes some UB which might have been causing issues for some people.
2. Adds as0 which can be used with handwritten asm if desired.
3. Binaries are now stripped so are smaller overall.

### CODE REVIEW

**Review by Dragorn421 — APPROVED** [review]
Nice :clap: 

Worth mentioning this updates to https://github.com/decompals/ido-static-recomp/releases/tag/v0.2 , leaving out acpp, copt, upas (not that I know why / what these are for anyway)
Besides as0, this also adds ujoin, uld, usplit (again idk what these are) which were already in the repo for some ido hosts/versions but not all :shrug: 

Seeing how the recomp seems to be actively going, and this isn't urgently needed, maybe we could wait a bit for recomp to settle down before updating? But it's not a big deal to merge this now and update again later too if something else comes up :shrug: 

Side note, out of curiosity I checked if this performed better but no surprise building from clean is the same time with master's or this pr's recomp

**Comment by AngheloAlf** [comment]
- `acpp`: a C preprocessor, but it isn't used by default by IDO (it uses `cfe` as the C preprocessor)
- `copt`: a C-to-C "optimizer". From what I have heard most of the time it produces worse codegen and makes code harder to decompile. As a reference SM64 audio code was compile with this enabled. You can toy with it by passing `-sopt`
- `upas`: the Pascal equivalent to `cfe` (`cfe` is the C front end)
- `ujoin`: No clue. @EllipticEllipsis was trying to investigate what it was, maybe he has more info about it. I think it was speculated to _join_ multiple compiled binaries into one or something among those lines
- `usplit`: No idea either. I think it was speculated to do the opposite stuff to `ujoin`
- `uld`: Required for `-O3`

Elliptic also found this diagram which is kinda neat and can help to understand the subprograms flow (It comes from the [MIPS Compiling and Performance Tuning Guide](https://irix7.com/techpubs/007-2479-001.pdf)):
image

**Comment by EllipticEllipsis** [comment]
Yes, `ujoin`/`usplit` are also needed for -O3: since decomp.me has the newest version, you can see what is used for each set of flags with `-show`:
```
cc: Warning: -c should not be used with ucode -O3 -o32 on a single file; use -j instead to get inter-module optimization.
/usr/lib/cfe -D_MIPS_FPSET=16 -D_MIPS_ISA=2 -D_ABIO32=1 -D_MIPS_SIM=_ABIO32 -D_MIPS_SZINT=32 -D_MIPS_SZLONG=32 -D_MIPS_SZPTR=32 -D__EXTENSIONS__ -DLANGUAGE_C -D_LANGUAGE_C -D__INLINE_INTRINSICS -Dsgi -D__sgi -Dunix -Dmips -Dhost_mips -D__unix -D__host_mips -D_SVR4_SOURCE -D_MODERN_C -D_SGI_SOURCE -D_PIC -D__DSO__ -DSYSTYPE_SVR4 -D_SYSTYPE_SVR4 -D_LONGLONG -D__mips=2 -I -D_MIPSEB -DMIPSEB -D__STDC__=1 -I/usr/include /var/folders/7b/687bcx9x7k3g7jmpldxdd3xc0000gn/T/tmpew8xetvk/code.c -Xv -D_CFE -Amachine(mips) -Asystem(unix) -Xwoff649,838,712 -call_shared -G 0 -std -XS/tmp/ctmstBasxdD -Xcpluscomm -mips2 -EB -Xg0 -O3 > /tmp/ctmfZidTlj 
cfe: parse_command /usr/lib/ujoin -v -mips2 -o code.u /tmp/ctmfZidTlj /tmp/ctmstBasxdD 
/usr/lib/uld -L/usr/lib/ -_SYSTYPE_SVR4 -require_dynamic_link _rld_new_interface -mips2 -call_shared -g0 -no_AutoGnum -preserve_dead_code code.u -ko /tmp/ctmluJxa5yf 
/usr/lib/usplit -v -mips2 -o /tmp/ctmsbtkbPF -t /tmp/ctmstBasxdD /tmp/ctmluJxa5yf 
/usr/lib/umerge -v -Olimit 5000 -mips2 -EB -g0 -O3 /tmp/ctmsbtkbPF -o /tmp/ctmm6trry0 -t /tmp/ctmstBasxdD 
  parse_command
/usr/lib/uopt -v -G 0 -Olimit 5000 -mips2 -EB -g0 -O3 /tmp/ctmm6trry0 /tmp/ctmooSbe4t -t /tmp/ctmstBasxdD /tmp/ctmosv8sSZf 
uopt: parse_command(2947) 
/usr/lib/ugen -v -G 0 -pic1 -mips2 -EB -g0 -O3 /tmp/ctmooSbe4t -o /tmp/ctmclgl1rG -t /tmp/ctmstBasxdD -temp /tmp/ctmgtmX44Tp 
ugen: parse_command
/usr/lib/as1 -t5_ll_sc_bug -elf -pic1 -v -G 0 -p0 -r4300_mul -r4300_mul -mips2 -EB -g0 -O3 -Olimit 5000 /tmp/ctmclgl1rG -o /var/folders/7b/687bcx9x7k3g7jmpldxdd3xc0000gn/T/tmpew8xetvk/object.o -t /tmp/ctmstBasxdD 
as1: parse_command
```

IDO `cc`'s manual lists what each program is for, although some of the descriptions are rather vague:
```
     file.c		  input	file
     file.o		  object file
     a.out		  loaded output
     /tmp/ctm*		  temporaries
     /usr/lib/cpp	  C macro preprocessor
     /usr/lib/acpp	  ANSI/ISO C macro preprocessor
     /usr/lib/pca	  multiprocessing analyzer (Power C only)
     /usr/lib/mpc	  multiprocessing C translator (Power C	only)
     /usr/lib/copt	  C source-to-source optimizer
     /usr/lib/cfe	  C front end
     /usr/lib/ujoin	  binary ucode and symbol table	joiner
     /usr/bin/uld	  ucode	loader
     /usr/lib/usplit	  binary ucode and symbol table	splitter
     /usr/lib/umerge	  procedure intergrator
     /usr/lib/uopt	  optional global ucode	optimizer
     /usr/lib/ugen	  code generator
     /usr/lib/as0	  symbolic to binary assembly language translator
     /usr/lib/as1	  binary assembly language assembler and reorganizer
     /usr/lib/mcrt1.o	  startup for profiling
     /usr/lib/crt1.o	  runtime startup
     /usr/lib/crtn.o	  runtime startup
     /usr/lib/libc.a	  standard library, see	intro(3)
     /usr/lib/libcmp.a	  multiprocessing library (Power C only)
     /usr/lib/libc.so.1	  shared standard library
     /usr/lib/libfpe.a	  floating point exception handler library, see
			  sigfpe(3c)
     /usr/lib/libgl.so	  IRIS-4D shared graphics library
     /usr/lib/libm.a	  math library
     /usr/lib/libm.so	  shared math library
     /usr/lib/libprof1.a  level	1 profiling library
     /usr/include	  standard directory for `#include' files
     /usr/bin/ld	  loader
     mon.out		  file produced	for analysis by	prof(1)
     /usr/bin/cord	  procedure rearranger
```

**Review by AngheloAlf — APPROVED** [review]

**Review by fig02 — APPROVED** [review]
> Seeing how the recomp seems to be actively going, and this isn't urgently needed, maybe we could wait a bit for recomp to settle down before updating?

Think the phantom bug fix makes it worth it to bring this in asap (assuming it is actually fixed, would still be good to test our old cutscene header example)

**Comment by Roman971** [comment]
Was anyone able to test building on macos and windows with the new binaries? I doubt it would have issues but we might want to make sure before merging, or at least plan to test it soon

**Comment by EllipticEllipsis** [comment]
Mac is fine, I've been working on recomp on Mac so I've tested these at some point. For Windows I don't think we know anyone who uses it?

**Comment by fig02** [comment]
This has been confirmed to fix the phantom bug issue from z64cutscene_commands.h. thanks to g0zar from the discord for testing :)
(also I agree with merging without testing windows, i know 0 people who use it)

**Review by Roman971 — APPROVED** [review]

**Pull request merged**
