### PR TITLE
Bg_Hidan_Kowarerukabe OK

### PR DESCRIPTION
**Pull request by Zelllll**
Fire Temple Breakable Walls and Floors, all functions OK and documented

### CODE REVIEW

**Review by AdamKiddle — CHANGES_REQUESTED** [review]
Is it weird that I've kinda been looking forward to seeing this this actor decomped for quite a while? Maybe I'm going crazy...

Thanks for releasing this one! I left some feedback on stuff like compiler warnings and style choices.

I also show you how to re-write these double loops in a cleaner way (these general rotation operations happen quite often across the codebase and they're often implemented in the same way each time)

**Comment by Zelllll** [comment]
Thanks a lot for all the suggestions! Looks like one of your suggestions is causing the PR to not build anymore though, I'll look into it later.

**Review by fig02 — APPROVED** [review]

**Comment by fig02** [comment]
need to merge master and update math functions

**Comment by Zelllll** [comment]
Alright all the math stuff is merged in and conflicts are resolved, should be good to merge

**Review by Roman971 — APPROVED** [review]

**Pull request merged**
