### PR TITLE
Document object_gndd (Young Ganondorf)

### PR DESCRIPTION
**Pull request by tom-overton**
A companion piece to #1345. I documented the younger Ganondorf's object as well, since many textures were similar or identical to the older Ganondorf.

### CODE REVIEW

**Review by fig02 — APPROVED** [review]

**Review by Roman971 — APPROVED** [review]
Some of these names are too long imo (eg. `gYoungGanondorfHorsebackMagicChargeUpStartAnim`), but I guess we will just have to consider using shorter prefixes or omitting some terms

**Comment by tom-overton** [comment]
I suppose I could omit "magic" from that one, since he doesn't charge anything else up. What do you think, @Roman971 ?

**Comment by fig02** [comment]
it could possibly be mistaken for the horse "charging", like running away/charging, dunno
its probably fine to omit it, but yeah. overall I think longer anim names arent a *huge* issue, cause they are usually only referenced a few times

**Comment by tom-overton** [comment]
Ah, yeah, I didn't think about that, but you're right. And while Phantom Ganon is a completely separate object, he *does* charge at you on horseback. I suppose I'll keep the existing name for now.

**Pull request merged**
