### PR TITLE
Extract skyboxes and backgrounds

### PR DESCRIPTION
**Pull request by louist103**
At long last its here. Backgrounds and skyboxes extracted in beautiful RGBA32.

### CODE REVIEW

**Review by Dragorn421 — COMMENTED** [review]
Nice!

Should we have any `SplitTlut="false"`? Since it's the default it can be omitted afaik, but should it?

Is there any point to `number 0` (in the spec) besides a "cleaner" z64.map file?

**Comment by louist103** [comment]
> Nice!
> 
> Should we have any `SplitTlut="false"`? Since it's the default it can be omitted afaik, but should it?
> 
> Is there any point to `number 0` (in the spec) besides a "cleaner" z64.map file?

I added it to be consistent with the others but I have no attachment to it. 
I added number zero cause AFAIK its technically correct but it seems like I didn't add it for title cards, again I can take it out if needed.

**Comment by Dragorn421** [comment]
Did we agree on removing `number 0` from the spec in the end?

**Comment by louist103** [comment]
> Did we agree on removing `number 0` from the spec in the end?

I still personally think keeping `number 0` doesn't make the spec look cluttered enough to justify the map having nonsense values.
However I know the leads want it gone so if they want it gone I can remove it.

**Comment by fig02** [comment]
I think its probably best if `number 0` is removed
I dont have much of an opinion on the split TLUT thing in the xmls

also agree with romans comment above that needs to be addressed

**Comment by Dragorn421** [comment]
On `SplitTlut="false"` it will probably take a skybox documentation pass to tell if they should be kept (from what I'm seeing they should)
I'd keep them, we can remove them later if needed, it's easier than adding them back

**Review by fig02 — APPROVED** [review]

**Review by Roman971 — APPROVED** [review]

**Pull request merged**
