### PR TITLE
Name `ACTOR_FLAG_11` as `ACTOR_FLAG_ENKUSA_CUT`

### PR DESCRIPTION
**Pull request by Dragorn421**
My favourite actor flag

### CODE REVIEW

**Comment by fig02** [comment]
lol nice flag
we can probably go with bush instead of enkusa, at least imo

**Comment by Dragorn421** [comment]
I was thinking it was best to wait until we give the actors proper names, since there are other "bush" actors like [Wood02](https://github.com/zeldaret/oot/blob/master/src/overlays/actors/ovl_En_Wood02/z_en_wood02.c#L4) or [Hana](https://github.com/zeldaret/oot/blob/master/src/overlays/actors/ovl_Obj_Hana/z_obj_hana.c#L62)

**Comment by fig02** [comment]
I guess, but I think the "cut" gives you the context you need to know. I would also be ok with "grass", given thats what kusa translates to.
I also think this flag was probably not specifically meant for this one actor and probably had a larger meaning. But of course we cant really tell from the information we have

**Review by Roman971 — APPROVED** [review]
Either BUSH or the original actor name seem fine to me

**Review by fig02 — APPROVED** [review]
would prefer bush, but if the change will be made when we change actor names anyway then I wont push the issue

**Pull request merged**
