### PR TITLE
Renamed EVENTCHKINF_3C

### PR DESCRIPTION
**Pull request by JordanLongstaff**
Flag: Defeated Nabooru as Iron Knuckle
New name: `EVENTCHKINF_DEFEATED_NABOORU_KNUCKLE`

### CODE REVIEW

**Review by fig02 — APPROVED** [review]
This is commonly referred to as "Nabooru Knuckle" so I would probably prefer `EVENTCHKINF_DEFEATED_NABOORU_KNUCKLE`. but its fine if others dont agree

**Review by mzxrules — APPROVED** [review]

**Comment by fig02** [comment]
will bump my suggestion one more time, as I do prefer "Nabooru Knuckle" alot more. But ill merge in 24 hours if no response.

**Comment by fig02** [comment]
might need to format

**Comment by JordanLongstaff** [comment]
> might need to format

Sigh...it's _one space off_. 😡

**Comment by JordanLongstaff** [comment]
And yes, I know there's a script I can run locally to check formatting. It doesn't work on Windows, though.

**Pull request merged**
