### PR TITLE
[ntsc-1.0/1.1] Match audio library

### PR DESCRIPTION
**Pull request by cadmic**
It seems like the audio library changed twice, once for NTSC 1.1 and once for PAL 1.0. Strangely, the GC versions actually use the NTSC 1.0 version, so we have the ordering backwards currently. I wasn't sure how to represent the conditions in code, but I went with:

```c
#if OOT_VERSION < NTSC_1_1/PAL_1_0 || PLATFORM_GC
  // earlier audio versions (and GC)
#else
  // later audio versions
#endif

#if !(OOT_VERSION < NTSC_1_1/PAL_1_0 || PLATFORM_GC)
  // later audio versions only
#endif
```

### CODE REVIEW

**Review by Dragorn421 — COMMENTED** [review]
`#include "versions.h"` in include/tables/ files looks odd because those files are included to construct C source, probably should add a note in versions.h about it that it should only contain macro definitions and no "actual C"

sequence_table.h also is missing the include

**Review by Dragorn421 — COMMENTED** [review]
Also is there an opportunity here to introduce an AUDIO_LIBRARY_VERSION macro or similar in versions.h ? Maybe that would make the version ifdefing less weird

**Comment by cadmic** [comment]
> #include "versions.h" in include/tables/ files looks odd because those files are included to construct C source, probably should add a note in versions.h about it that it should only contain macro definitions and no "actual C"

Good point, I guess nothing else that the audio tables files depend on is `#include`d either so I removed the versions.h includes

> Also is there an opportunity here to introduce an AUDIO_LIBRARY_VERSION macro or similar in versions.h ? Maybe that would make the version ifdefing less weird

Maybe, I'm not really sure what to call the versions (note that 0.9 also has changes so does 1.0 use "audio library v2"?) or if the ifdefing here is worse than having to refer to another file to see what oot versions a change is in. What do others think?

**Comment by Dragorn421** [comment]
`AUDIO_LIBRARY_VERSION` could just be a number like 0 for "0.9", 1 for the next iteration we know of, then 2, etc. ?

**Comment by cadmic** [comment]
So something like this? https://github.com/cadmic/oot/commit/9703d741ca1bf35e90174bf32d807181f7a57d9b
My first impression is that it makes it pretty difficult to tell which OOT version these changes are actually in, compared to the more verbose way

**Comment by fig02** [comment]
I see both sides of the argument here. 
I think I lean slightly towards it being an improvement, anyone who gets deep into the weeds of audio code should be able to quickly internalize the gamecube version oddity. And its explained well in that comment you added.

**Comment by cadmic** [comment]
I'm not sure I'll be able to internalize that `AUDIO_LIBRARY_VERSION < 3` means `before PAL 1.0, or GameCube` though. I think I would have to refer to versions.h basically every time, which is an annoying step which breaks the flow of reading code

**Review by fig02 — APPROVED** [review]
we can look into the library version potentially later. but I see your points of why it may not be desireable

**Review by Dragorn421 — APPROVED** [review]

**Pull request merged**
