### PR TITLE
Add clean assets

### PR DESCRIPTION
**Pull request by louist103**
Added `make cleanassets` so that deleting tools isn't needed to clean up assets.

### CODE REVIEW

**Review by Zelllll — APPROVED** [review]
Good idea, I think there could be a better name for it though, maybe make clean-all or something?

**Comment by louist103** [comment]
> 
> 
> Good idea, I think there could be a better name for it though, maybe make clean-all or something?

We already have distclean which clean everything (tools, assets and runs `make clean`)

**Comment by AngheloAlf** [comment]
What if `cleanassets` would also delete `build/assets/`? Just to be sure you get rid of every asset-related file.
Also, I don't like the name `cleanassets`, but that's personal taste, but I don't have any better suggestion.

**Comment by fig02** [comment]
I personally dont see cleaning just assets on its own to be needed, but I may be missing some use cases. `distclean` seems fine for this job imo

**Comment by AngheloAlf** [comment]
One use case could be testing changes made to ZAPD. At least I tend to delete that folder multiples times while adding stuff to ZAPD and testing everything is still OK.

**Comment by fig02** [comment]
thats fair. I guess distclean works well for me cause doing setup is pretty fast, but that will vary for everyone

**Review by fig02 — APPROVED** [review]

**Comment by louist103** [comment]
> 
> 
> I personally dont see cleaning just assets on its own to be needed, but I may be missing some use cases. `distclean` seems fine for this job imo

The idea is when IDO is built during setup (and also removed with `distclean`) it will take much longer to rebuild all the tools so doing `distclean` will get very time consuming if all you want to do is clean assets.

**Review by Roman971 — COMMENTED** [review]
Ideally we shouldn't ever need to clean assets directly, but that will require some improvements to the process and tools, so I guess it's fine to have a command like this in the meantime.

Tho I don't think it needs to remove build/assets (seems unnecessary since files leftover in build are irrelevant), and it should probably be called `assetclean` for consistency with `distclean` and such

**Comment by louist103** [comment]
Its a nice thing to have when doing testing with ZAPD or if something goes wrong with asset extraction or something like that.  Mostly for the future when IDO is built it will take much longer to rebuild everything.
I can change the names for consistency.

**Review by Roman971 — APPROVED** [review]
Imo the `toolclean` recipe is unnecessary, but this looks fine to me either way

**Comment by fig02** [comment]
Would agree that it doesnt seem necessary

**Review by AngheloAlf — CHANGES_REQUESTED** [review]
Could you add the new rules to `.PHONY`?

**Review by AngheloAlf — APPROVED** [review]

**Comment by AngheloAlf** [comment]
What are we waiting for in this PR? It already has 2 leads approvals :thinking:

**Comment by fig02** [comment]
as mentioned above, still dont understand the addition of a recipe that cleans tools only, and dont find it very necessary

**Comment by louist103** [comment]
> 
> 
> as mentioned above, still dont understand the addition of a recipe that cleans tools only, and dont find it very necessary

Its really only there on the off chance it is needed one day.  I don't think it will be used very often though.

**Comment by fig02** [comment]
id add it when and if its needed then, personally

**Review by fig02 — APPROVED** [review]

**Review by Roman971 — APPROVED** [review]

**Pull request merged**
