### PR TITLE
Audio decomp, supersedes #1236

### PR DESCRIPTION
**Pull request by playerskel**
This PR supersedes #1236 by @MNGoldenEagle. I have tried to continue working on @MNGoldenEagle (and team)'s great work where they currently lack the time to finalize this PR for merging.

Some things covered here (in no particular order):
* removes whitespaces and weird characters in (auto-generated) filenames
* get rid of the ELF creation way of embedding data into the final ROM
* automatically generate the `audio_init_params.c` constants upon music (.aifc) changes
* apply some, but certainly not all, feedback from @Dragorn421 and @engineer124
* merged with the latest master branch

Not sure if it's ideal, but instead of creating ELF files I have now opted to generate C files directly from within the audio-related Python scripts. These are then compiled into object files etc. This can be improved further, but it works fairly well for now.

I'd be happy to apply other feedback or necessary changes, but I tried to steer away from making bigger picture decisions such as naming schemes etc that were mentioned in #1236. Will reply in #1236 to clarify what has been applied in this PR and what has not. Looking forward to feedback.

### CODE REVIEW

**Comment by krm01** [comment]
one issue that causes me lots of problems (using the old audio PR) is the python scripts don't clean up their temp files, and I ended up filling my WSL partition due to millions (literally) `MQDebug_xxxxxxxx_aseq` directories in my /tmp folder. sooo not sure if you explicitly addressed that with the new changes, but if not, i do recommend making the scripts clean up after themselves lol

**Review by engineer124 — COMMENTED** [review]
Thanks for this! I'll mess around with extraction in the coming days, but I'd still like to see all the audio tooling scripts in an audio folder `tools/audio/` to avoid clutter in the `tools/` directory

**Comment by playerskel** [comment]
@krm01 i did notice the same and removed _some_ temporary files, but not all; will definitely have another look and address this, good point
@engineer124 makes sense, agreed, will do

**Comment by ariahiro64** [comment]
https://user-images.githubusercontent.com/45049787/229369141-e25d6016-5f26-4422-bf37-714e0a0c0a03.mp4

after messing around i was able to replace voice clips

**Comment by playerskel** [comment]
@engineer124 @fig02 @Dragorn421 hey team, was wondering if there are concrete things we/I can work on to get this merged or if it's not yet entirely clear to the rest of the team (which I could understand too). There's always things to improve further, but the audio system works rather well and it should be fairly straightforward merge. So kind of wondering what can be done to get this going before the PR becomes stale and outdated etc. Thanks.

**Comment by RevoSucks** [comment]
Is there any update on this?

**Comment by Thar0** [comment]
I've done some work already to address some of the things above, such as the "drums and tuning values" issues and reworking the build system. If anyone would like to collaborate on those feel free to reach out.

We also need feedback from anyone who has already tried to use this and what their experiences were. What worked as expected? What caused problems? If you have used this, please comment or bring it up in the discord. It would be very helpful for determining further improvements.

**Comment by Dragorn421** [comment]
https://discord.com/channels/388361645073629187/882153990798848021/1128799336759836775

**Comment by HailToDodongo** [comment]
Few things i noticed while testing this:
- just compiling doesn't pick up any changes in .seq files, i have to run "setup" every time before compiling
- because setup ran, it will compile all sequences instead of only the ones i changed
- I also have a temp-file problem, every compile after a "setup" run creates exactly 4030 empty files in /tmp/
  - this also happens for non-audio changes, just with fewer files, the main repo does not have this problem

For the setup i made a smaller task just for the audio:
```makefile
setup_audio:
	python3 tools/audio/assemble_sequences.py assets/sequences build/include build
	python3 tools/audio/assemble_sound.py assets/soundfonts build/assets build/include assets/samples --build-bank --match=ocarina -q
```

For the temp files, no idea where they are from, but i was able to see a few with lsof before the process stopped:
```
/tmp  lsof -r1 ctm*
COMMAND    PID    USER   FD   TYPE DEVICE SIZE/OFF   NODE NAME
cfe     153941 mbeboek    1w   REG   0,35        0 162047 ctmf8xxGLE
cfe     153941 mbeboek    3w   REG   0,35        0 162047 ctmf8xxGLE

```
But i did not find any reference to "cfe" in the repo.

I'm testing directly on linux (arch).

**Comment by hensldm** [comment]
> Few things i noticed while testing this:
> 
>     * I also have a temp-file problem, every compile after a "setup" run creates exactly 4030 empty files in /tmp/
>       
>       * this also happens for non-audio changes, just with fewer files, the main repo does not have this problem
>  ...
>
> For the temp files, no idea where they are from, but i was able to see a few with lsof before the process stopped:
> 
> ```
> /tmp  lsof -r1 ctm*
> COMMAND    PID    USER   FD   TYPE DEVICE SIZE/OFF   NODE NAME
> cfe     153941 mbeboek    1w   REG   0,35        0 162047 ctmf8xxGLE
> cfe     153941 mbeboek    3w   REG   0,35        0 162047 ctmf8xxGLE
> ```
> 
> But i did not find any reference to "cfe" in the repo.
> 
> I'm testing directly on linux (arch).

This is due to outdated ido recomp binaries. The older version had a bug that would leave empty temp files around.

**Comment by HailToDodongo** [comment]
> > Few things i noticed while testing this:
> > ```
> > * I also have a temp-file problem, every compile after a "setup" run creates exactly 4030 empty files in /tmp/
> >   
> >   * this also happens for non-audio changes, just with fewer files, the main repo does not have this problem
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > ...
> > For the temp files, no idea where they are from, but i was able to see a few with lsof before the process stopped:
> > ```
> > /tmp  lsof -r1 ctm*
> > COMMAND    PID    USER   FD   TYPE DEVICE SIZE/OFF   NODE NAME
> > cfe     153941 mbeboek    1w   REG   0,35        0 162047 ctmf8xxGLE
> > cfe     153941 mbeboek    3w   REG   0,35        0 162047 ctmf8xxGLE
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > But i did not find any reference to "cfe" in the repo.
> > I'm testing directly on linux (arch).
> 
> This is due to outdated ido recomp binaries. The older version had a bug that would leave empty temp files around.

Ah thanks! just merged the latest master in, and the temp files are no longer created.

**Comment by Dragorn421** [comment]
This is going to be superseded by a newer audio extraction tooling effort
cf the discord for details

**Comment by fig02** [comment]
Hello,
We've officially begun merging Tharo's audio infrastructure to the codebase with https://github.com/zeldaret/oot/pull/2008

Thank you for your work on this, and @MNGoldenEagle for work on the original iteration of this. 
This will be closed now, but everyone's work does not go unappreciated :)

**Pull request closed without merging**
