### PR TITLE
Rename Math3D_CylOutsideCyl and Math3D_CylOutsideCylDist

### PR DESCRIPTION
**Pull request by cadmic**
The comments on these functions seem wrong, I'm pretty sure these functions test if the two cylinders are overlapping, not if the cylinders are outside each other. I tried to rename them to be consistent with the SphVsCyl functions above.

### CODE REVIEW

**Comment by cadmic** [comment]
I've agreed to the contributor agreement above

**Review by Dragorn421 — APPROVED** [review]
Nice catch!

**Comment by fig02** [comment]
(disclaimer i dont follow much of the math thats actually happening in these functions)
Looking at the family of related functions:
```
s32 Math3D_SphVsSphOverlap(Sphere16* sphereA, Sphere16* sphereB, f32* overlapSize);
s32 Math3D_SphVsSphOverlapCenter(Sphere16* sphereA, Sphere16* sphereB, f32* overlapSize, f32* centerDist);

s32 Math3D_SphVsCylOverlapDist(Sphere16* sph, Cylinder16* cyl, f32* overlapSize);
s32 Math3D_SphVsCylOverlapCenterDist(Sphere16* sph, Cylinder16* cyl, f32* overlapSize, f32* centerDist);

s32 Math3D_CylVsCylOverlapDist(Cylinder16* ca, Cylinder16* cb, f32* overlapSize);
s32 Math3D_CylVsCylOverlapCenterDist(Cylinder16* ca, Cylinder16* cb, f32* overlapSize, f32* centerDist);
```
Is there any reason why only sphere vs sphere is the only one that wouldnt need to specify "dist"?
Feel like we can maybe remove dist from the other two?

**Comment by cadmic** [comment]
One difference is that the SphVsSph functions compute xyz overlap/dist while SphVsCyl and CylVsCyl compute xz overlap/dist only. But maybe a comment is enough for that?

How about these names:

```
s32 Math3D_SphVsSphOverlap(Sphere16* sphereA, Sphere16* sphereB, f32* overlapSize);
s32 Math3D_SphVsSphOverlapDist(Sphere16* sphereA, Sphere16* sphereB, f32* overlapSize, f32* centerDist);
s32 Math3D_SphVsCylOverlap(Sphere16* sph, Cylinder16* cyl, f32* overlapSize);
s32 Math3D_SphVsCylOverlapDist(Sphere16* sph, Cylinder16* cyl, f32* overlapSize, f32* centerDist);
s32 Math3D_CylVsCylOverlap(Cylinder16* ca, Cylinder16* cb, f32* overlapSize);
s32 Math3D_CylVsCylOverlapDist(Cylinder16* ca, Cylinder16* cb, f32* overlapSize, f32* centerDist);
```

**Comment by Dragorn421** [comment]
I think a comment is enough for the xz / xyz differences, these aren't functions called from many spots (only from the collider and collision systems in fact)

For the function names I'm not sure, it may change again later but for now maybe this:
```c
s32 Math3D_AaaVsBbbOverlap(a, b, f32* overlapSize)
s32 Math3D_AaaVsBbbOverlapCenterDist(a, b, f32* overlapSize, f32* centerDist)
```

**Review by Dragorn421 — APPROVED** [review]

**Review by Thar0 — APPROVED** [review]

**Review by fig02 — APPROVED** [review]

**Pull request merged**
