### PR TITLE
pushed -> push for player push/wind variables

### PR DESCRIPTION
**Pull request by fig02**
didnt notice this when reviewing, but imo this makes more sense as "push" instead of "pushed". You will be actively pushed when these are set, so current tense makes more sense imo

### CODE REVIEW

**Comment by EllipticEllipsis** [comment]
Isn't the point that it's passive (which of course uses the past participle, as you do in the comments)? It's pushing *of* Player, not something being pushed *by* Player (i.e. the DoAction Push, which no doubt has its own tangled set of variables somewhere that could naively get mixed up with it when someone's trying to read it in a year's time).

**Comment by fig02** [comment]
I read it as the current push speed and push direction of the player.
You dont say "im setting the pushed speed of the player", its "im setting the push speed and push direction"

**Comment by EllipticEllipsis** [comment]
That's a noun phrase, then.

**Comment by fig02** [comment]
if this was a readout of the speed after something else already pushed it, then "pushedSpeed" would make more sense, but you set this to actually do the pushing, its the push speed

**Comment by fig02** [comment]
the comment is in past tense cause its describing the effect of what will happen after you set it. after you set the push speed, player is pushed at that speed
we can try to reword the comment to make that more clear if needed, but I dont think past tense is correct for the variable itself

**Comment by engineer124** [comment]
The motivation for using `pushedSpeed` over `pushSpeed` was that without context, I would think `pushSpeed` would be referring to the speed at which player is pushing a block, in that it's the speed at which player is "pushing". Randomizer for example changes the speed at which player pushes a block.

Using "pushed" was a subtle way to avoid that confusion, to emphasize that Player was "being pushed" instead of player "pushing". I'm happy to use something else other than `pushedSpeed`, but I would find `pushSpeed` a little confusing as well

**Comment by fig02** [comment]
I think with the comment explaining what it means its fine personally, but yeah if we can find something new that helps with both concerns then we can change it. 
But yea pushed speed to me doesnt make it clear that its the value that gets used for the pushing, its sounds like a passive readout of the speed after the pushing occurs

**Comment by fig02** [comment]
I think I agree that moving away from push is probably better as a whole. will close until we come up with a new term

**Pull request closed without merging**
