### PR TITLE
Fully macrofiy `gSaveContext.inventory.equipment`

### PR DESCRIPTION
**Pull request by Dragorn421**
To me this is questionable

to-do (in future PRs if this gets in):
```
inventory.upgrades
inventory.questItems
inventory.dungeonItems
inventory.dungeonKeys
equips.equipment
sceneFlags
worldMapAreaData
```

### CODE REVIEW

**Comment by hensldm** [comment]
Out of curisoity what seems questionable about this to you? Seems relatively fine to me.

**Comment by Dragorn421** [comment]
I think there's little value in macroifying simple single-bit operations, the macros don't abstract much if anything, basically to me it looks like `#define ADD(a,b) ((a)+(b))`
They're also not used a whole lot so it's not expected to eventually be familiar with them like some other macros

And I would if this gets in generalize this approach to other data (see top comment) which would be that much more clutter

So why did I open this PR if I'm not too hot on the proposed changes, well I forgot unfortunately. I think it was in context of other changes, maybe saveContext substructs and/or inventory code documentation?

**Comment by engineer124** [comment]
The conversation that led to this PR starts here: https://discord.com/channels/688807550715560050/688851317593997489/1028003702067445810

The premise is how much of `gSaveContext` do we want to macrofy with getters and setters? Because of the number of `(void)0, ` accesses required (at least in MM, iirc it's a bit less in OoT), do we ever want to access `gSaveContext` directly or should all accesses be macrofied? If not, what should be macrofied and what shouldn't?

**Comment by hensldm** [comment]
It might be better to just close this PR for now, and possibly open a new one around the ones that should actually be macro'd after having the discussion brought up by engineer.

**Comment by fig02** [comment]
Id agree. I am just going to go ahead and do that, we can have this discussion at a later time.

**Pull request closed without merging**
