### PR TITLE
Add Arch Linux build support

### PR DESCRIPTION
**Pull request by nathanjensen1**
Modified Makefile to support Arch Linux's mips binutils prefix and add Arch Linux package install commands to README.md.
I have verified that the modified Makefile continues to work with Ubuntu

### CODE REVIEW

**Review by Dragorn421 — APPROVED** [review]

**Comment by OctopusET** [comment]
You can also use this package
https://aur.archlinux.org/packages/mips-linux-gnu-binutils/

**Comment by nathanjensen1** [comment]
The package I used in my changes to the README has the higher popularity score and has been dutifully maintained since 2015. More people use it, so it seemed like the right choice

**Review by Dragorn421 — COMMENTED** [review]
#1076 supersedes the makefile changes this PR has in that #1076 would allow `make MIPS_BINUTILS_PREFIX=mips-elf`

As for the Arch-specific instructions in the readme we seem to be leaning (?) towards not providing explicit instructions for environments other than Ubuntu (i.e. Ubuntu in WSL) since no active contributor can really maintain support for it

So if others get the same feeling we may just close this

**Comment by deadmeu** [comment]
> As for the Arch-specific instructions in the readme we seem to be leaning (?) towards not providing explicit instructions for environments other than Ubuntu (i.e. Ubuntu in WSL) since no active contributor can really maintain support for it

I always appreciate when projects include installation instructions for Arch even if it's just a one-liner. I'm sure the community will maintain it given how many people (especially gamers) use Arch-based distros.

**Comment by fig02** [comment]
apologies for a very late review on this. 

We restructured our readme a bit and how we handle dealing with other platforms in general. We now support adding instructions for other more niche platforms (they go in docs/). You can add the arch specific instructions there and link to them as a bullet point under the installation section of the readme

**Comment by nathanjensen1** [comment]
I added the Arch build instructions to docs/BUILDING_ARCHLINUX.md and the link to the README. The existing Linux link has been unchanged and the Arch Linux link has been placed beneath it.
It may be helpful to clarify that "Linux" means Debian/Ubuntu and not Linux more broadly

**Comment by Dragorn421** [comment]
Feel free to take the opportunity of this PR to clarify those spots that use "Linux" too broadly

Once #1076 is merged it will be possible to do `make MIPS_BINUTILS_PREFIX=mips-elf-`, or easier to change `MIPS_BINUTILS_PREFIX` to that in the Makefile, and this PR will need to be updated to take that into account (instead of checking for `mips-elf-ld`)

To be clear this PR would then only provide additional instructions with no Makefile changes, hopefully that works for you?

**Comment by fig02** [comment]
(1076 has been merged, and agreed on the above)

**Comment by fig02** [comment]
will probably be closing this soon due to inactivity, but if you feel like reopening this with the suggested changes at a later time feel free to

**Comment by fig02** [comment]
closed per above, feel free to repoen if you want

**Pull request closed without merging**
