### PR TITLE
Introduce version-specific YAML config

### PR DESCRIPTION
**Pull request by cadmic**
It would be nice to have a central place to configure version-specific info for asset extraction. This would eventually include:
* DMA table offset and segment names (for baserom segment extraction)
* Virtual address for each DMA segment (for asset extraction)
* Address of `gMtxClear` (for asset extraction)
* Addresses of text tables (for text extraction)
* Offsets and sizes of assets in code/overlays
* Offsets and sizes of .incbin segments
* Some way to version asset XMLs?

This PR introduces a YAML file in `baseroms/VERSION/config.yml`, and a Python module to make it easy to work with. Currently this is hooked up in `decompress_baserom.py`, `extract_baserom.py`, and `msgdis.py`. I ended up splitting the DMA segment names and virtual addresses into a separate CSV file though: the huge config looked really ugly as YAML, and parsing the giant YAML file took a pretty long time (300ms or so) compared to CSV.

### CODE REVIEW

**Comment by AngheloAlf** [comment]
> parsing the giant YAML file took a pretty long time (300ms or so) compared to CSV

You can speed up yaml parsing by adding an `import pylibyaml` just before the actual `import yaml`

iirc, the `yaml` python module is a pure Python implementation, while `pylibyaml` is a C implementation which can patch the `yaml` lib in runtime so it uses the C implementation instead

**Comment by cadmic** [comment]
Thanks, I haven't tried it but I guess yaml parsing speed isn't a factor. I still found it pretty ugly to have all the DMA segments in config.yml though, it takes up several thousand lines while the rest of the config is like 6 llines

**Review by fig02 — APPROVED** [review]

**Review by Dragorn421 — APPROVED** [review]
low effort approval

**Review by hensldm — APPROVED** [review]
LGTM

**Pull request merged**
