### PR TITLE
Set __FILE__ in asm_processor

### PR DESCRIPTION
**Pull request by zelda2774**
Alternative to #791. (Though that PR may still be useful.)

### CODE REVIEW

**Comment by louist103** [comment]
The only issue is that it still has the random characters at the end of the file.  Thats something they wanted to avoid.

**Comment by zelda2774** [comment]
The idea of this is to set `__FILE__` to equal the original filename, before preprocessing. So while the file getting compiled would still have random characters in its name, it wouldn't show up in error messages or in `__FILE__`. 

The CI failure is apparently due to `#line` introducing bss reorderings...

**Review by louist103 — APPROVED** [review]

**Comment by louist103** [comment]
After this is merged in I may make the build.py change so the temp files have a recognizable name.  Unless you want to do it your self.

**Comment by zelda2774** [comment]
> After this is merged in I may make the build.py change so the temp files have a recognizable name. Unless you want to do it your self.

Please go ahead if you want, it sounds like a useful change.

**Comment by AngheloAlf** [comment]
> The asm_processor.py we use is a straight copy from its repo (https://github.com/simonlindholm/asm-processor), so this change should probably be PR'd and merged in its master branch before porting it over.
- Roman, 24/04/2021, 6 hours ago

**Comment by zelda2774** [comment]
Done

**Review by fig02 — APPROVED** [review]

**Review by Thar0 — APPROVED** [review]

**Review by Roman971 — APPROVED** [review]
This seems fine to me. I'm worried it will cause issues with bss ordering in the future and might be straight up incompatible with some files, but I guess we'll deal with that if it happens

**Comment by AngheloAlf** [comment]
How can setting a macro can cause bss ordering issues? :thinking:

**Comment by Roman971** [comment]
> How can setting a macro can cause bss ordering issues? 🤔

The #line directive isn't a macro, and it looks like it has the same effect as a .bss variable or external pointer reference, which can cause bss reorderings in large files. Some of these reorderings are necessary so we sometimes need a specific amount of variables/references (see the extra dummy variables in z_parameter.c and z_collision_check.c), which might be impossible to reach with an extra #line directive.

**Pull request merged**
