### PR TITLE
Make Python multiprocessing scripts Windows-compatible

### PR DESCRIPTION
**Pull request by JordanLongstaff**
The `fork` context is the default for Unix, but doesn't work on Windows. For Windows, it's `spawn`.
Removing the `fork` argument from the `get_context` calls makes them return the default context.

### CODE REVIEW

**Comment by fig02** [comment]
In isolation this change seems fine, but is there a point if the rest of the entire build system still assumes a unix/linux context?
Most people on windows work on this project with WSL, I would recommend the same so you can build the changes you make (and be able to run all the tools as needed)

**Comment by AngheloAlf** [comment]
I don't think removing `fork` is a good idea.

It is true that currently it is the default on Linux, but it is not the default on Mac. The default one for Windows and Mac is `spawn`, which is slower than `fork` since it is starting a whole new process [according to the docs](https://docs.python.org/3/library/multiprocessing.html#multiprocessing-start-methods).

I think not being the default method on Mac is the reason why we are using `fork` explicitly, specially given the PR that introduced it is specifically for building on Macs https://github.com/zeldaret/oot/pull/1086

The docs also mention that in a future Python version no platform will default to `fork`, so even Linux users will get an slower extraction.

The asset extraction script has a fallback way to allow doing extraction without multiprocessing in platforms that do not support  `fork` like Windows. It was introduced in this PR https://github.com/zeldaret/oot/pull/1513. It may be better to implement something similar in the format script too.

**Comment by cadmic** [comment]
IIUC some scripts require `"fork"` so that some file descriptors are inherited properly by the spawned processes (hence why we need to override the default for macOS). So it's not just a performance issue, it's a functional issue too. I forget the details though

**Comment by JordanLongstaff** [comment]
> I want to recommend again that you set up WSL on windows

I have now installed WSL on my computer. I'll close this PR and try out WSL as soon as I have some time and energy.

> He is struggling to get the right clang format version working, so these changes are a result of the wrong one being used.

Version 15 made the fewest changes of any version I've seen. Version 16 doesn't remove that change, but also adds more.
Like you say, I'm probably best off using WSL and figuring out the necessary tweaks from there.

**Comment by fig02** [comment]
just for your reference, its version 14. idk if you are in the discord yet, but feel free to join and we'll direct you to how to install that on WSL.

**Pull request closed without merging**
