### PR TITLE
Rename EVENTCHKINF_02

### PR DESCRIPTION
**Pull request by JordanLongstaff**
Flag: First spoke to Mido
New name: `EVENTCHKINF_MIDO_DENIED_DEKU_TREE_ACCESS`

### CODE REVIEW

**Review by fig02 — APPROVED** [review]
thanks for splitting it up!

If you want to do a few at a time in a more logical grouping, like all of the mido related flags in one PR for example, I think thatd be fine. But even one at a time is much easier to review!

**Comment by hensldm** [comment]
FWIW: MM decided to name flags like this `TALKED`, rather than `FIRST_SPOKE`. For example we would probably name this `EVENTCHKINF_TALKED_MIDO`

**Comment by mzxrules** [comment]
we probably wouldn't name it just `EVENTCHKINF_TALKED_MIDO` because Mido has multiple conversations. Additionally, the flag isn't tracking if the player had ever talked to Mido.

More precisely... 

* `EVENTCHKINF_02` is specifically tracking if Mido has denied the player access to the Great Deku Tree. This checked by Saria, changing her response to the player by acknowledging what has happened. 

* `INFTABLE_0C` performs a role role that is more in line to talking to Mido, in that it tracks that the longer conversation was spoken once, and swaps to the alternate shorter message. 

Both events will be skipped if you talk to Mido with a Kokiri Sword and Deku Shield.

**Comment by fig02** [comment]
Good catch-- I also tried to investigate closer and saw that it would change sarias dialogue to you. But didnt realize it would be skipped if you already had sword and shield.
`EVENTCHKINF_MIDO_DENIED_DEKU_TREE_ACCESS` I guess

**Comment by JordanLongstaff** [comment]
> If you want to do a few at a time in a more logical grouping, like all of the mido related flags in one PR for example, I think thatd be fine. But even one at a time is much easier to review!

Who knows what the best way is to split them up. I realize one at a time would be more PRs, more work, and more chance of merge conflicts (since many of them are on consecutive lines). But it's also smaller chunks of work and it just seemed like the safest way to go.

**Review by fig02 — APPROVED** [review]

**Comment by fig02** [comment]
I think you can use your judgement for what makes sense to group together. If there are a bunch of flags that are grouped in the same area in the game, or all serve the same purpose (like boss defeated flags, or something), then they can happen at once

A handful of flags grouped together is still very manageable to review in a batch. The original PR was just a bit too much.

**Comment by JordanLongstaff** [comment]
> For example we would probably name this `EVENTCHKINF_TALKED_MIDO`

I notice that the flag for first speaking to Malon is called `EVENTCHKINF_TALKED_TO_MALON_FIRST_TIME`. Should I rename this to `EVENTCHKINF_TALKED_TO_MIDO_FIRST_TIME`?

**Comment by cadmic** [comment]
> Who knows what the best way is to split them up. I realize one at a time would be more PRs, more work, and more chance of merge conflicts (since many of them are on consecutive lines). But it's also smaller chunks of work and it just seemed like the safest way to go.

Here's some suggestions for groups based on #2299:

* Area entrance cutscenes
* Skulltula rewards
* Mask trading quest
* Boss battles 
* Dodongo's cavern story flags
* Jabu Jabu story flags

stuff like that. A good litmus test is if you can describe the changes in the space of one commit message (72 characters).

Ironically, splitting related changes up too much can slow down review, because reviewers may suggest one thing in the first PR, then change their mind after seeing more context in a later PR. Ideally you could anticipate what objections your reviewers might have, and try to group things so that you'd only need to edit things in one place if they request changes.

As an author, I like splitting projects into small PRs because it means less PR edits when discussions happen faster, and less merge conflicts since changes get merged faster. But as you point out, splitting too much can be counterproductive on both of those fronts.

**Comment by fig02** [comment]
"Should I rename this to `EVENTCHKINF_TALKED_TO_MIDO_FIRST_TIME`"
No, as discussed above this flag is actually more specific than just "talked to mido for the first time". Its talked to mido specifically without sword and shield, and got denied access to the deku tree.
We will have to work out a consistent naming for "first time" flags in other contexts, though (that can happen separately from this PR)

**Review by mzxrules — APPROVED** [review]

**Pull request merged**
