### PR TITLE
Name asset extraction tools more consistently

### PR DESCRIPTION
**Pull request by cadmic**
Now they're all run as `$(PYTHON) tools/extract_foo.py`.

### CODE REVIEW

**Comment by hensldm** [comment]
For the text, I like doing something similar to audio. Have the two scripts in a folder called text, than create an extract_text.py outside it that parses the config for what the text extract script needs, and calls msgdis's main function (in <https://github.com/zeldaret/mm/pull/1750> I renamed it to extract).

**Comment by cadmic** [comment]
hm, I think that could make sense if the main function was identical to MM's like with the audio tools. Otherwise, I think the extra indirection is not worth it.

Either way, could we consider that out-of-scope for this PR?

**Comment by cadmic** [comment]
> The main function in msgdis.py should be the same.

hm, I tried a simple `diff` and it didn't show that many similarities (and in MM it seems to be split into nes/msgdisNES.py and staff/msgdisStaff.py too)

> mainly so we don't have to rename msgdis.py to extract_text.py and than rename it back to msgdis.py

Why's that? I don't think an extra commit would cost that much

**Comment by cadmic** [comment]
are you concerned about losing history due to git shenanigans if we rename it later and aren't careful?

**Comment by hensldm** [comment]
> hm, I tried a simple diff and it didn't show that many similarities (and in MM it seems to be split into nes/msgdisNES.py and staff/msgdisStaff.py too)

Think you are outdated. Updated version should just have `msgdis.py` and `msgenc.py` in `tools/text`

> Why's that? I don't think an extra commit would cost that much

More so personal preference of keeping the git history cleaner.
However if other people have the same opinion that this is out of scope, I won't hold it back.

**Comment by cadmic** [comment]
> Think you are outdated. Updated version should just have msgdis.py and msgenc.py in tools/text

Ah yeah, my bad. It still seems like a bit of work to factor out all of the differences though

> More so personal preference of keeping the git history cleaner.

I'm also a fan of a clean git history, although my idea of that is:

1. Every change builds (makes bisecting possible)
2. Every change has a clear commit message
3. Every change is as self-contained as possible and only does one thing

Number 3 there is often at odds with minimizing the total number of commits. For example, I think this change would be better as "name asset extraction tools more consistently" instead of "name asset extraction tools more consistently, and also prepare for unifying OOT and MM text extraction".

(As an aside, in the same vein I much prefer a bunch of 1-line commits rather than "Misc Cleanup", since mixing changes together like that makes it harder to read the history.)

**Review by Thar0 — APPROVED** [review]
It's a bit of a shame that the two message tools are not next to each other anymore but it's not a huge deal I guess

**Review by fig02 — APPROVED** [review]

**Pull request merged**
