### PR TITLE
Native MacOS build support

### PR DESCRIPTION
**Pull request by ethteck**
The time of MacOS support is upon us.

I had to make some changes to the Makefile to support the weird diferences in some tools. I also updated the readme to add some Mac setup help and remove the docker-sync stuff.

The spec comment move was necessary due to the empty line left after removing that comment causing some issues in the spec parser.

### CODE REVIEW

**Comment by i82orbom** [comment]
Nice! Unfortunately I'm missing mips-linux-gnu, what'd be the replacement for mac?

**Comment by FryJay** [comment]
I'm running into the same issue.

**Comment by ethteck** [comment]
@i82orbom @FryJay hey guys, sorry .. knew I was forgetting something. I need to write a guide / script for how to crosscompile mips-linux-gnu-binutils. I'll do that sometime tonight or tomorrow and tag you again when it's in the PR.

**Comment by FryJay** [comment]
Thanks for your work on this.  It'll be awesome to have it working on my laptop.

**Comment by i82orbom** [comment]
@ethteck thanks for taking care of this!

**Comment by FryJay** [comment]
The binutils build seems to work though it ends with "Nothing to be done for 'install' but that might be for a specific subdirectory because a bunch of stuff is installed.  When I run gmake setup though, I get a lot of these messages:

```
tools/ZAP2/ZAP2.out e -i scenes/xml/dungeons/ganon_tou.xml -b baserom/ -o scenes/dungeons/ganon_tou -gsf 1 -sm tools/ZAP2/SymbolMap_OoTMqDbg.txt
sh: tools/ZAP2/ZAP2.out: cannot execute binary file
```
which also appear if I attempt a gmake -j.  Make produces the same error.

**Comment by FryJay** [comment]
I also tried the commands in the new guide using gmake in case that made a difference but that only seemed to result in minor output changes but no changes to the outcome.

**Comment by FryJay** [comment]
After cleaning and remaking ZAP2 like you suggested, I can now successfully build the project on my laptop.

**Comment by i82orbom** [comment]
@FryJay did you see this error?

/bin/sh: line 0: cd: testsuite: No such file or directory
make[2]: *** [all-subdir] Error 1
make[1]: *** [all-libiberty] Error 2
make: *** [all] Error 2

I'm currently trying to build, but I can't, I tried to disable libiberty, but it's needed by other stuff...

**Comment by FryJay** [comment]
No I don't think I ran into that one.

**Review by FryJay — APPROVED** [review]

**Review by i82orbom — APPROVED** [review]
Great job! thanks a lot

**Review by Roman971 — APPROVED** [review]

**Review by fig02 — APPROVED** [review]

**Comment by i82orbom** [comment]
@ethteck I'm not sure if this is related to the mac build or my setup, but I'm getting issues using the diff script, it can't find any symbol, whereas with the build from the docker it can...

**Comment by fig02** [comment]
have you ran make and updated expected/ lately?

**Comment by i82orbom** [comment]
Setting this env vars in the bash profile solved the issue:

export LANG="en_US.UTF-8"
export LC_ALL=c

Diff.py is checking for some english fixed strings in the .map file, having a different locale will generate translations for those strings, making the diff script not work.

**Review by i82orbom — APPROVED** [review]

**Pull request merged**
