### PR TITLE
Put comments on player's `sAgeProperties` with field name

### PR DESCRIPTION
**Pull request by Dragorn421**
Now 1000% more reader friendly

Should I also name the anim fields with temporary names based on the oot3d animation names, like I did in #1446 ?

### CODE REVIEW

**Review by engineer124 — APPROVED** [review]

**Review by fig02 — APPROVED** [review]
kinda wonder what left-aligned /* */ would look like, but either is fine

**Review by hensldm — APPROVED** [review]

**Comment by Dragorn421** [comment]
Alternatives:
- "above with breaks": https://github.com/zeldaret/oot/compare/master...Dragorn421:oot:doc_mark_age_props_fields_abovewithbreaks
- "left": https://github.com/zeldaret/oot/compare/master...Dragorn421:oot:doc_mark_age_props_fields_left
- "above" (no breaks)

**Comment by fig02** [comment]
personally im fine with keeping what the pr has and revisiting when all members are named

**Comment by Dragorn421** [comment]
Imminent button press then :+1:

**Pull request merged**
