### PR TITLE
[wip] Fix Sun extract 

### PR DESCRIPTION
**Pull request by MegaMech**
The sun extraction was fairly wonky. I recommend using Texture64 as you can see all the possible sizes at the same time

### CODE REVIEW

**Comment by AngheloAlf** [comment]
There's a reason why we are extracting those textures this way.
The sun textures of gameplay keep are a bit special. If you take a look at the generated C file for that object (`assets/objects/gameplay_keep/gameplay_keep.c`), you'll see the dlists which load the texture load them as individual textures, not as a big chunk.

**Comment by Emill** [comment]
That could be fixed by making the other two point to the base address plus an offset.

Note that the same sun texture is also referenced by the forest fairies. At that time the whole texture is loaded in one go.

**Comment by tom-overton** [comment]
We talked about it on Discord, but this is not going to work until ZAPD is changed to support array offsets in textures.

**Comment by MegaMech** [comment]
I'm confident that zapd will have an update for this soon. So maybe just leave this open for now.

**Comment by MegaMech** [comment]
Also, the sun is being extracted as i4 instead of i8

**Comment by MegaMech** [comment]
I disagree.

**Comment by MegaMech** [comment]
image
i4

**Comment by MegaMech** [comment]
i8
image

**Review by Dragorn421 — COMMENTED** [review]
To give actual context to these changes,

-----------

For some reason `gSunDL` uses `gSunTex` and `gSunEveningTex` in fragments, of weird sizes (64x32, 64x17, 64x17) and in the wrong format (i8 instead of i4).
afaik this is the actual dlist used for drawing the overworld sun, so idk how this turns out to not be an issue visually

<details>

<summary>
gSunDL:
</summary>

```c
Gfx gSunDL[] = {
    gsSPMatrix(0x01000000, G_MTX_NOPUSH | G_MTX_MUL | G_MTX_MODELVIEW),
    gsDPPipeSync(),
    gsDPLoadTextureBlock(gSun1Tex, G_IM_FMT_I, G_IM_SIZ_8b, 64, 32, 0, G_TX_NOMIRROR | G_TX_CLAMP, G_TX_NOMIRROR |
                         G_TX_CLAMP, 6, 5, G_TX_NOLOD, G_TX_NOLOD),
    gsDPLoadMultiBlock(gSunEvening1Tex, 0x0100, 1, G_IM_FMT_I, G_IM_SIZ_8b, 64, 32, 0, G_TX_NOMIRROR | G_TX_CLAMP,
                       G_TX_NOMIRROR | G_TX_CLAMP, 6, 5, G_TX_NOLOD, G_TX_NOLOD),
    gsSPVertex(gameplay_keepVtx_04D348, 12, 0),
    gsSP2Triangles(0, 1, 2, 0, 2, 1, 3, 0),
    gsDPLoadTextureBlock(gSun2Tex, G_IM_FMT_I, G_IM_SIZ_8b, 64, 17, 0, G_TX_NOMIRROR | G_TX_CLAMP, G_TX_NOMIRROR |
                         G_TX_CLAMP, 6, 5, G_TX_NOLOD, G_TX_NOLOD),
    gsDPLoadMultiBlock(gSunEvening2Tex, 0x0100, 1, G_IM_FMT_I, G_IM_SIZ_8b, 64, 17, 0, G_TX_NOMIRROR | G_TX_CLAMP,
                       G_TX_NOMIRROR | G_TX_CLAMP, 6, 5, G_TX_NOLOD, G_TX_NOLOD),
    gsSP2Triangles(4, 5, 6, 0, 6, 5, 7, 0),
    gsDPLoadTextureBlock(gSun3Tex, G_IM_FMT_I, G_IM_SIZ_8b, 64, 17, 0, G_TX_NOMIRROR | G_TX_CLAMP, G_TX_NOMIRROR |
                         G_TX_CLAMP, 6, 5, G_TX_NOLOD, G_TX_NOLOD),
    gsDPLoadMultiBlock(gSunEvening3Tex, 0x0100, 1, G_IM_FMT_I, G_IM_SIZ_8b, 64, 17, 0, G_TX_NOMIRROR | G_TX_CLAMP,
                       G_TX_NOMIRROR | G_TX_CLAMP, 6, 5, G_TX_NOLOD, G_TX_NOLOD),
    gsSP2Triangles(8, 9, 10, 0, 10, 9, 11, 0),
    gsSPEndDisplayList(),
};
```

</details>

-----------

`gSunTex` is also used by `z_object_kankyo` to draw the yellow "fairies" particle effects in kokiri forest and lost woods (unless I'm mistaking those for something else), this time with the correct I4 64x64 format and dimensions though:

https://github.com/zeldaret/oot/blob/a160fb96c86a191f887bea1ec7e078218902922c/src/overlays/actors/ovl_Object_Kankyo/z_object_kankyo.c#L495

```c
Gfx gKokiriDustMoteTextureLoadDL[] = {
    gsDPSetCombineLERP(PRIMITIVE, ENVIRONMENT, TEXEL0, ENVIRONMENT, PRIMITIVE, 0, TEXEL0, 0, PRIMITIVE, ENVIRONMENT,
                       TEXEL0, ENVIRONMENT, PRIMITIVE, 0, TEXEL0, 0),
    gsDPLoadTextureBlock_4b(0x08000000, G_IM_FMT_I, 64, 64, 0, G_TX_NOMIRROR | G_TX_CLAMP, G_TX_NOMIRROR | G_TX_CLAMP,
                            G_TX_NOMASK, G_TX_NOMASK, G_TX_NOLOD, G_TX_NOLOD),
    gsSPEndDisplayList(),
};
```

---------

@MegaMech you would also need to update `gSun1Tex` to `gSunTex` in `z_object_kankyo.c`. That's why jenkins (the automated build for matching rom check) fails.

EVEN THEN, zapd (the tool that extracts assets), wouldn't be able to extract `gSunDL` properly (it would need to use for example `&gSunTex[some number]` in place of the current `gSun2Tex`, and that isn't something it handle at the moment at least)

I would open an issue on the zapd repo about handling this maybe if it isn't already handled in recent zapd revisions, and close this pr until zapd supports what's needed

**Comment by MegaMech** [comment]
Yes, thank you. I am aware of everything you mentioned but thanks for showing that in a manner that will help everyone else understand.

I have already opened an issue for zapd. I might make a PR for a fix. But I'm not familiar with zapd. Theoretically it shouldn't be too hard to fix for someone whose already familiar with it.

**Pull request closed without merging**
