### PR TITLE
Rename PLAYER_STATE1_13

### PR DESCRIPTION
**Pull request by JordanLongstaff**
State: Hanging off ledge
New name: `PLAYER_STATE1_HANGING_OFF_LEDGE`

### CODE REVIEW

**Comment by fig02** [comment]
This goes for all of these Player state flag PRs you are opening-- I would really prefer if the code surrounding them is documented at the same time. With many of these there are tons of uses in undocumented code that we have to either take your word for, or do the very laborious work of verifying all use cases. 

This is not as much of an issue with the event flags youve been documenting, as they often have 1 or two uses across different actors. But player state flags are a bit different.

You can correct me if I'm wrong, but I get the feeling youre just copying these flag names from another source, not verifying the validity yourself, is that fair to say?

**Comment by JordanLongstaff** [comment]
I've been copying them from SoH, which is obviously easy to mass produce, but I do intend to verify them myself.
The mass production stage is almost done. There are only a few flags left that I want to copy over, and they too will be verified.

**Comment by fig02** [comment]
I dont agree with this approach really, I would rather the code that deals with these flags be documented and the flags be named as a by product of that. It makes way more sense to document the action functions themselves within player that these correspond to, doing it this way is a bit backwards.

I am documenting player as an ongoing effort, and would be down to accept help if you want to collaborate on this. But I dont want to just name these and take the existing documentations word for it.

**Comment by JordanLongstaff** [comment]
So, FWIW, I discovered that SoH added these names in HarbourMasters/Shipwright#2765 and, ironically, they credited this repo.

**Comment by fig02** [comment]
Yeah its probably pieced together from various external research like the spreadsheets linked in this discord message: https://discord.com/channels/688807550715560050/915273929369731173/1079468306219679827

But they arent named in the repo yet for a reason. Those are only tentative names, guessed by various testing in game. Which often times does not capture the full scope of a flags purpose. Instead, it makes more sense to document the code surrounding the flags purpose along side it, which is how all the flags named so far have been done. 

This is an ongoing process and should not be rushed by throwing these names in, in my opinion. 

Some of the flags youve opened PRs for are small enough in scope and could be verified with the current state of Player's documentation. But for the others, I will not personally be reviewing until player documentation is in a better state to allow it.

**Comment by fig02** [comment]
As for this specific PR, it falls under the same umbrella as ledge climbing for me and needs more documentation.

**Comment by JordanLongstaff** [comment]
Listen, thanks so much for reviewing these, but they're in the way of other PRs, including a few of mine. I'm going to close them, do a closer inspection with better documentation once I get a chance, and then reopen them.

**Comment by fig02** [comment]
Alright. The ones that I did leave review on I'm confident in naming now. And since I've already done the work of confirming their validity, I will probably open PRs myself for them shortly.

**Pull request closed without merging**
