### PR TITLE
Decompiled some of z_bgcheck.c

### PR DESCRIPTION
**Pull request by arthurtilly**
Migrated my changes from the old repo. Finished with decomping for a little while due to lack of motivation.

### CODE REVIEW

**Comment by fig02** [comment]
not sure why jenkins failed, I got OK on my end

**Comment by mzxrules** [comment]
I've pulled this into my own branch at https://github.com/mzxrules/oot/tree/z_bgcheck

I'd rather finish BgCheck than try and fix this up, because it'd be better to figure out the proper types through decomp than to go through the process of making it acceptable for the repo when it's half complete.

**Comment by ethteck** [comment]
Makes sense @mzxrules. In that case, should we close this PR?

**Comment by fig02** [comment]
We are going to close this for now. Mzx has taken this into his own hands and will fix up the PR to be mergeable in the process of decomping the rest of the file.

**Pull request closed without merging**
