### PR TITLE
Document player attribute: blue warp position

### PR DESCRIPTION
**Pull request by JordanLongstaff**
This attribute is the position of a blue warp that has spawned in the same room as Link.

### CODE REVIEW

**Comment by JordanLongstaff** [comment]
Or so I think. It is that in many cases, but there are others where I'm less sure.

**Comment by fig02** [comment]
This is much more than the blue warp position, yeah. It's more generally the "target position" link should walk to when automatically walking. Used by doors, cutscenes, blue warps, walking into and leaving areas, to name a few.

I am working toward documenting this, but it's pretty complicated and needs normal walking to be documented first. I would prefer to close this and come back to it when it makes sense.

**Comment by fig02** [comment]
In general if you want to work on player things, I would recommend you join the discord and talk with me about it first. I actively have my hand in multiple parts of player at the moment, and have a generalized plan of how to proceed with player docs in an order of different sub systems that makes sense.

**Comment by JordanLongstaff** [comment]
Is there a specific channel to talk about it in? I'm already in the Discord server and I see channel names like `oot-decomp`, `oot-decomp-help` and `oot-names-discussion`.

I'd be remiss if I didn't point the irony of the fact that the ambiguities are all in `z_player.c`. 😂

**Comment by fig02** [comment]
oot-decomp is fine to talk about general things and for planning out stuff. 
oot-decomp-help is specifically for matching things
oot-names-discussion is for talking about what to name things

Can you type in the discord so I know who you are? There is no user that I can see with your github username

**Comment by fig02** [comment]
Once again will ask, please type something in the oot channel so I know which discord user you are!

**Pull request closed without merging**
