### PR TITLE
Audio WIP

### PR DESCRIPTION
**Pull request by krimtonz**
Decompiles several audio functions, as well as some naming fixes.

### CODE REVIEW

**Review by fig02 — COMMENTED** [review]
just a few comments regarding naming conventions. Imo alot of these names you have in comments can probably just be implemented, but if you just want to get this in so other people can take it over, I understand

**Review by fig02 — APPROVED** [review]
I removed the prefixes from all of the struct variable names

**Review by Thar0 — APPROVED** [review]

**Review by Roman971 — COMMENTED** [review]
Looks good to me overall, tho I haven't looked too much at the actual audio code since I know it's still a WIP.
I just have a few minor suggestions

**Comment by fig02** [comment]
changes made

**Review by Roman971 — APPROVED** [review]

**Pull request merged**
