### PR TITLE
Naming a function

### PR DESCRIPTION
**Pull request by Ozero4**
func_800F8884 to Audio_CheckAndCleanSfxBank

### CODE REVIEW

**Comment by cadmic** [comment]
FYI the build failed because it wanted you to rename it in tools/disasm/ntsc-1.2/functions.txt too

**Comment by Ozero4** [comment]
Ok Thanks

**Review by fig02 — APPROVED** [review]
would like if any audio experts could take a look and confirm, but it seems to make sense to me

**Comment by Thar0** [comment]
This sounds wrong to me based on the function args. The function to be renamed has arguments `u8 bankId, Vec3f* pos`. The proposed name reads to me as "check and clean [a particular] sfx bank", as in to check and clean an entire bank. What this function really seems to do is to remove any sfx entry if the position of the sfx matches the input position, which isn't represented by this name. Majora's Mask names this `AudioSfx_StopByPosAndBankImpl` which is in line with what this function does, and its use in `Audio_StopSfxByPosAndBank`. For OoT we have slightly different names in this file to MM currently, so I'd suggest adapting the MM name to `Audio_StopSfxByPosAndBankImpl`.

fwiw, I'd probably have named this something like `Audio_RemoveSfxFromBankByPos`, just because I think it's nice to try to avoid the `<name>Impl` pattern as much as possible.

**Review by cadmic — APPROVED** [review]

**Review by fig02 — APPROVED** [review]
I think I prefer sticking with MM on this until we change it in both places, but its fine

**Pull request merged**
