### PR TITLE
Remove THIS macro

### PR DESCRIPTION
**Pull request by fig02**
This is something we've mentioned in passing here and there, but now that all actors are done I think its a good time.
Not everyone may be aware of this planned change, so this PR also serves as a discussion starter if need be.

My opinion on the matter:
This macro made sense to have while we were decompiling things, its a construct we had to type often. But long term, I think it hides information that is useful to see on the surface without needing a macro. Seeing that upcast from Actor* to the specific actor is important, and not really that verbose.
Additionally, the same thing will happen for gamestate -> globalCtx, and I dont think we plan to introduce a macro for that.

Thanks to tharo for helping me make a script to do this, im a pepega when it comes to making tools lol

### CODE REVIEW

**Review by Dragorn421 — APPROVED** [review]
I thought there were a lot of actors using inlined `THIS` due to regalloc or stack not allowing a `this` temp,
but that actually only happens in `BgMizuMovebg_Init` (which now looks extra bad)

**Comment by fig02** [comment]
yea, and that one we believe to be a fake match and can hopefully be removed

**Review by Roman971 — APPROVED** [review]

**Comment by mzxrules** [comment]
I'm gonna miss THIS

**Review by louist103 — APPROVED** [review]
The end of an era.

**Review by petrie911 — APPROVED** [review]

**Review by engineer124 — APPROVED** [review]

**Pull request merged**
