### PR TITLE
Document entrances 0x7FF9-0x7FFF as "Return Entrances"

### PR DESCRIPTION
**Pull request by Dragorn421**

### CODE REVIEW

**Comment by fig02** [comment]
naming them "Exit Entrances" is a problem for two reasons imo:
exit has a meaning in scenes with the exit index/list
"entrance exit" are opposites of each other, so it sounds kinda strange

imo naming it like "return entrance" or something would possibly be better, cause its an entrance that returns you to the right place that you came from in shared scenes

**Review by fig02 — APPROVED** [review]

**Review by Roman971 — APPROVED** [review]
I wonder if these values should be part of the main enum, but I guess that would only matter when using the enum as a type, so it's probably fine either way

**Comment by fig02** [comment]
it probably makes more sense separate, cause they dont mean anything to the entrance system/table. They only have meaning within player

**Comment by Roman971** [comment]
It's true that they are translated by the player system but they are still intended to be used everywhere else, alon with other entrance indexes (eg. scene exit lists), so I don't know if it's right to treat them as separate

**Pull request merged**
