### PR TITLE
Automatic objects 2

### PR DESCRIPTION
**Pull request by AngheloAlf**
Adds an XML to every remaining object and adds them to the spec.

### CODE REVIEW

**Review by fig02 — APPROVED** [review]

**Comment by petrie911** [comment]
BTW, object_bv and object_mo are already part of their respective boss PRs.

**Comment by AngheloAlf** [comment]
If they get merged first, I can remove them.
If this get merged first, they can either ignore this and use their XML, or use the XML from here to improve theirs in case they missed something. It isn't a big deal imo

**Review by EllipticEllipsis — APPROVED** [review]
IMO this shouldn't include the ones that are already in PRs, but it's not a big problem.

**Comment by fig02** [comment]
Excluding the ones in prs is reasonable.
I only suggested getting them all in so we can be 100% sure we have them all. But I definitely expect all the ones open to get in sooner than later, so it would help avoid conflicts

**Comment by AngheloAlf** [comment]
So, I would just need to exclude object_bv and object_mo?

**Comment by AngheloAlf** [comment]
Do we want an XML for `gameplay_object_exchange_static`? I think it is the only one missing of the `gameplay_` stuff.
I know it only has zeroes, but we could just extract a small blob and add it to the spec.

**Review by Roman971 — APPROVED** [review]

**Comment by fig02** [comment]
think we can probably wait on the exchange static stuff, we still need to talk about how we're going to make use of them and stuff. soon though

**Pull request merged**
