### PR TITLE
Renamed EVENTCHKINF_33

### PR DESCRIPTION
**Pull request by JordanLongstaff**
Flag: King Zora moved (or gave letter to King Zora)
New name: `EVENTCHKINF_GAVE_LETTER_TO_KING_ZORA`

### CODE REVIEW

**Comment by mzxrules** [comment]
Some extra information: 

With this event, both 'King Zora Moved' and 'King Zora received Ruto's Letter' are fairly accurate descriptions within the scope of King Zora.

Outside of him, they appear to be used for the dialog of a generic Zora in Zora's Domain (guessing based on the script). Here the event swaps the dialog of the Zora, but the usage is a little weird from a game design perspective

* Initially, the Zora says something to the effect of "some of us have searched [for Ruto] as far as Lake Hylia", a hint on where to find the Ruto Letter
* Once set, the Zora says something to the effect of "would you send any clues about Ruto to King Zora?", which is odd since it seems to provide a hint on where to bring Ruto's Letter, but it isn't possible to see this dialog until after the bottle is returned.

**Review by fig02 — APPROVED** [review]
following the pattern we are starting to establish, this can be `_MOVED_KING_ZORA`, but dont care too much

**Comment by JordanLongstaff** [comment]
Wouldn't that imply that _we_ moved him? Maybe it should be `GAVE_LETTER_TO_KING_ZORA` instead?

**Comment by fig02** [comment]
I dont think it implies that, and i mean, you did make him move as the player. But sure, thats fine too.

**Comment by fig02** [comment]
bumping this as well, feel free to change to your new suggestion.

**Review by mzxrules — APPROVED** [review]

**Pull request merged**
