### PR TITLE
`InitVars` -> `Profile`

### PR DESCRIPTION
**Pull request by fig02**
This is a rare case of an original name actually being pretty good.

The intent here is "profile" means a high level overview of the vital parts of an actor/effect that are needed for it to run. I think it sounds better than "InitVars" and think we should use it too.

This diff is huge and not very review-able. I tried to make the commits split by each rename to make it easy to see what I did.

---

Theres proof in oot itself that this was the original name: `PRINTF(VT_COL(RED, WHITE) "データバンク無し！！<データバンク＝%d>(profilep->bank=%d)\n" VT_RST, objectSlot, profile->objectId);`

Animal Forest/Animal Crossing confirm this with, for example, the data symbol names:
`  0000e4a0 000024 0000e4a0  4 Player_Profile 	m_player_call.o`

The gamecube titles even have a similar concept of profiles (and their symbol names confirm they were also called profiles).
Here is an example of Player's profile in The Wind Waker
```c
static actor_method_class2 l_daPy_Method = {
    (process_method_func)daPy_Create,
    (process_method_func)daPy_Delete,
    (process_method_func)daPy_Execute,
    (process_method_func)daPy_IsDelete,
    (process_method_func)daPy_Draw,
};

actor_process_profile_definition2 g_profile_PLAYER = {
    /* LayerID      */ fpcLy_CURRENT_e,
    /* ListID       */ 5,
    /* ListPrio     */ fpcLy_CURRENT_e,
    /* ProcName     */ PROC_PLAYER,
    /* Proc SubMtd  */ &g_fpcLf_Method.base,
    /* Size         */ sizeof(daPy_lk_c),
    /* SizeOther    */ 0,
    /* Parameters   */ 0,
    /* Leaf SubMtd  */ &g_fopAc_Method.base,
    /* Priority     */ 0x0068,
    /* Actor SubMtd */ (actor_method_class*)&l_daPy_Method,
    /* Status       */ fopAcStts_FREEZE_e,
    /* Group        */ fopAc_PLAYER_e,
    /* CullType     */ fopAc_CULLBOX_0_e,
    /* field_0x30   */ 2,
};
```
Not that any of this matters for the argument of using it as a name, I just find it cool 😄

### CODE REVIEW

**Comment by Dragorn421** [comment]
It is a good name
You missed some _InitVars in the decomp tutorial

**Comment by fig02** [comment]
I purposefully did not change those-- feels weird to keep it up date with large name changes like this, to me those docs are frozen in time for the purpose they were written. But if people want me to still change it I can

**Comment by Dragorn421** [comment]
above discussion about updating the tutorial resolved on discord by agreeing to open #2013

Hence it'd be better to merge #2013 first

**Review by Dragorn421 — APPROVED** [review]

**Comment by fig02** [comment]
fwiw I dont think waiting is necessary. if this goes first, there wont be any conflicts with #2013 because this doesnt touch the tutorial. If for whatever reason we end up keeping it, we can just make the necessary updates.
But either way, am still hoping for a bunch more reviews on this before proceeding anyway.

**Review by krm01 — APPROVED** [review]
i have to admit this isn't really my favorite rename, but i understand the reasoning behind it. maybe i just need to get used to it more and i'll feel differently. my reasoning is that `InitVars` was dead simple and immediately obvious what its purpose was, even knowing nothing else about the actor system. i think "profile" also makes it seem like this struct has meaning during the actor's lifecycle, which is not true, the data is just copied out of it during init.

that said... i don't dislike it nearly enough to try to argue against it or further defend `InitVars` :)

**Comment by fig02** [comment]
All fair points. I think InitVars is way too robotic/literal, more than it needs to be. And even then it doesnt convey to me that its the high level overview of its operation/vital points in the way profile does to me. 
Being in sync with almost every other zelda decomp project in existence (that uses real names) is a nice plus, but obviously not the main point :)

**Review by hensldm — APPROVED** [review]
Name change seems fine to me :)

**Review by tom-overton — APPROVED** [review]

**Comment by cadmic** [comment]
I don't have comments on the actual change (if pressed I'd say I'm slightly negative because I don't think the change is worth it), but I think the changes to the tutorial should be reverted. It's weird that the variable names are "frozen in time" but the type names aren't. And it would remove any conflicts with #2013 so the PRs don't have to wait for one another

**Comment by fig02** [comment]
I didnt realize there were any changes to the tutorial-- my intention was there to be none. they got in on accident

**Comment by fig02** [comment]
fixed

**Review by mzxrules — APPROVED** [review]
I'm fine with it, and it doesn't seem like there's anything being merged accidentally.

**Pull request merged**
