### PR TITLE
Have tools construct paths in extracted/

### PR DESCRIPTION
**Pull request by cadmic**
While setting up PAL N64 assets, I found myself running `extract_incbins.py`, `msgdis.py`, and `extract_assets.py` manually a lot when iterating on the configs. Running a full `make setup` is too slow, and passing the paths manually is tedious because there's only correct choice and there's a lot of redundancy. I moved the string "extracted" to a common place so at least it's a little principled?

Partial revert of #2017

### CODE REVIEW

**Comment by Dragorn421** [comment]
Alternative solution to "it's slow or tedious":

1)
```sh
make --dry-run --always-make setup
```
aka `make -nB setup`

2) copy the commands you want to run

3) paste into a shell script file

4) run the script as much as you want

**Comment by cadmic** [comment]
those steps also sound slow and tedious

**Comment by cadmic** [comment]
I wasn't just running the same command over and over again, I had different programs (extract_assets.py, extract_incbins.py, msgdis.py), different flags (e.g. `-s`), and different versions (pal-1.0, pal-1.1, gc-eu at least). Editing the command line is a whole lot easier than editing a script and then running it, and editing the command line is a lot easier if you only have to specify the version once instead of 3 times

**Comment by krm01** [comment]
didn't we just do the opposite of this? lol i don't really care one way or another (i guess if you forced me choose to I'd say it's better to have the paths passed in)

however doing it for some tools and not all is definitely the worst outcome

**Comment by cadmic** [comment]
Yeah, I'm trying to partially revert it. I don't think there's anything inherently wrong with that, it seems like we'd discourage experimentation if we don't allow changes to be reverted.

I don't mind doing it for all the tools, that would also remove the need for `make setup-audio` too I think

**Comment by krm01** [comment]
what about creating new phony targets to run these scripts? is that worth considering?

**Comment by cadmic** [comment]
Yeah I don't see why it would not be worth considering. It has some downsides though, like not supporting `extract_assets.py -s`, and I think it would duplicate all the commands in both the new phony targets and `make setup` (or recursive `make`, ew) because I'm not sure how to get the dependencies to work when running `make setup` but not when you want to run a step manually

**Comment by cadmic** [comment]
Alright I tried to do the same treatment with all the tools. I think the Makefile looks cleaner now at least, though perhaps we should also rename `extract_assets.py -> tools/extract_assets.py`, `tools/msgdis.py -> tools/extract_test.py`, and `tools/audio_extraction.py -> tools/extract_audio.py`

**Comment by fig02** [comment]
id be fine with those renames (with the text typo fixed ofc)
`extract_assets.py` is currently in root cause some people find themselves needing to run it often. I don't tho, cause i dont do much asset work. Will the people who call this script on its own be bothered by the slightly longer path?

**Comment by cadmic** [comment]
Personally, I've been running it a lot, and honestly I'm more tripped up that it's not in `tools/` like the rest than having to type `tools/`. I think I'd like to leave the renames for another PR though, and keep this focused on "should it be easy to run the extraction tools manually, or should you use some indirection like a custom shell script or separate make target?"

**Comment by fig02** [comment]
Makes sense to both points. Am in favor.
I dont have much to say on this PR. Would like more input from dragorn who made the other changes regarding paths.

**Comment by hensldm** [comment]
Fully agree with the renames and moving extract_assets.py to tools (just did that for MM). 
With regards to this whole discussion though, I wouldn't be opposed to a new phony target that extracts all the assets (assets, text, and audio). I am a bit biased however, as I championed that for MM back in the day with my only regret being the name (something like extract would be much better than assets which can be misleading). On the other hand if you want a phony target that just calls extract_assets.py for example, you can use `.make_options.mk` to add your own phony target (tested and it works just fine by copy pasting the extract_assets.py command). I'll admit it doesn't work too well with single mode (though that in principle can be done) but with timestamp detection I've generally not used single mode myself all that often.

**Comment by cadmic** [comment]
These seems unpopular and I've worked around it for most of the multiversion stuff (by patching this commit into my dev branch)

**Pull request closed without merging**
