### PR TITLE
Download EGCS binutils and gcc for iQue

### PR DESCRIPTION
**Pull request by cadmic**
I don't personally plan to wire these up immediately, but at least it's possible now.

```bash
$ tree tools/egcs
tools/egcs
└── macos
    ├── addr2line
    ├── ar
    ├── as
    ├── cc1
    ├── cc1plus
    ├── cccp
    ├── cpp
    ├── cxxfilt
    ├── g++
    ├── gcc
    ├── ld
    ├── nm
    ├── objcopy
    ├── objdump
    ├── ranlib
    ├── readelf
    ├── strings
    └── strip
```

### CODE REVIEW

**Comment by cadmic** [comment]
(thanks to @AngheloAlf for help making macos releases for these)

**Review by AngheloAlf — APPROVED** [review]

**Review by Thar0 — APPROVED** [review]

**Comment by fig02** [comment]
Will this be downloaded for any version during setup? If so, does it make sense to put it behind an ique version so it only happens for `make setup VERSION=ique` (whatever both ique version names will actually be called)

**Comment by cadmic** [comment]
Yeah, it will download if you run `make setup` for any version (although only once ever, until you `distclean`). I'm not sure if it's worth making more complicated, it's only about 6-7 MB and takes less than 2 seconds for me

**Comment by fig02** [comment]
I just dont see ique being a very common version being built by others. I would prefer it only be done when needed, but not going to pursue it too hard

**Pull request merged**
