### PR TITLE
Mark func_800DC910 as NON_EQUIVALENT

### PR DESCRIPTION
**Pull request by louist103**
Also fixed a function call.

### CODE REVIEW

**Review by Dragorn421 — APPROVED** [review]
imagine building with -D NON_MATCHING

<details>



</details>

this meme was made by the OK gang

**Review by AngheloAlf — APPROVED** [review]

**Comment by fig02** [comment]
were we able to identify what exactly is non equivalent? 
i dont understand how the gcc testing being done was able to identify that this was non equiv. think itd be good to try to identify the exact problem and potentially try to fix it

**Comment by louist103** [comment]
> 
> 
> were we able to identify what exactly is non equivalent?
> i dont understand how the gcc testing being done was able to identify that this was non equiv. But i havent really been keeping up with that stuff.
> Think itd be good to try to identify the exact problem and potentially try to fix it

The GCC testing is how I got the idea to test this.  IDO crashes with this as well if thats what you meant.  The only thing GCC has to do with this is that it enables NON_MATCHING and NON_EQUIVALENT. 
Ill take a look at the function but given its size IDK if I will be able to fix it.

**Comment by fig02** [comment]
oh it crashes with ido, ok
yeah you dont need to look into it alot if you dont want to. but a quick look at the crash debugger might reveal an obvious problem

**Comment by louist103** [comment]
> 
> 
> oh it crashes with ido, ok
> yeah you dont need to look into it alot if you dont want to. but a quick look at the crash debugger might reveal an obvious problem

yeah so the debugger doesn't show up even with the and removing the button thing.

**Review by fig02 — APPROVED** [review]

**Review by Roman971 — APPROVED** [review]

**Pull request merged**
