### PR TITLE
Mention why PrimDepth is used in `PreRender_FetchFbufCoverage`

### PR DESCRIPTION
**Pull request by Thar0**
Crazy undocumented blender hardware behavior

### CODE REVIEW

**Review by Dragorn421 — COMMENTED** [review]
angrylion somehow knows about this but only for depth compare enabled
https://github.com/ata4/angrylion-rdp-plus/blob/c24268bddd44bcbb7f7d7f91b51dd30a6a92566b/src/core/n64video/rdp/zbuffer.c#L240-L252

it would be clearer to mention the coverage shift applies on the 8-bits value blender input, since with coverage you typically think of the 3-bits value

you could actually write a whole blog article on this, which makes me wonder if it's that useful to point out here without external references or additional details?

**Comment by Thar0** [comment]
I don't think additional details are especially needed, I only want to explain this particular usage of SetPrimDepth and I think the comment does this adequately. The only sources I can link are implementations in accurate graphics plugins since nobody has written about this otherwise. I'm happy to do so if it would be useful.

**Comment by Dragorn421** [comment]
To be sure, your comment goes against angrylion's code about "doesn't matter if depth compare", so angrylion has this wrong?

**Comment by Thar0** [comment]
The angrylion source implements this here
https://github.com/ata4/angrylion-rdp-plus/blob/c24268bddd44bcbb7f7d7f91b51dd30a6a92566b/src/core/n64video/rdp/zbuffer.c#L349-L365

**Review by fig02 — APPROVED** [review]

**Review by Dragorn421 — APPROVED** [review]

**Review by engineer124 — APPROVED** [review]

**Pull request merged**
