### PR TITLE
isTargeted -> isLockedOn [Target Docs 6/?] 

### PR DESCRIPTION
**Pull request by fig02**
This is a find and replace PR:
`actor.isTargeted` -> `actor.isLockedOn`
`Actor_IsTargeted` -> `Actor_IsLockedOn`
`Actor_OtherIsTargeted` -> `Actor_OtherIsLockedOn`

Its come to my attention that `Actor_IsLockedOn` and `Actor_OtherIsLockedOn` are probably inaccurate names. It checks `PLAYER_STATE1_4` which seems to be "is locked onto an enemy". However the rabbit hole goes deep on this, and we need to figure out how we are naming `ACTOR_FLAG_0`, `ACTOR_FLAG_1`, and `ACTOR_FLAG_2` to proceed. 

It is ignored in this PR to avoid scope creep, this just changes Targeting to LockOn for a few things.

### CODE REVIEW

**Review by cadmic — APPROVED** [review]
Don't think it was necessarily inaccurate before, if target means either lock-on or parallel, then the only way an actor can be targeted is if it's locked on. I think "targeted" is probably more familiar to readers but I guess they'll have to learn the lock-on terminology anyway

**Comment by fig02** [comment]
My inaccuracy comment is on the fact that the two functions only concern enemies (actors with `ACTOR_FLAG_2`)

**Comment by cadmic** [comment]
Right, just commenting on if `Actor_IsTargeted` was inaccurate originally

**Comment by fig02** [comment]
I see. Yeah it doesnt make sense to keep this generalized as target when we will be (and already have) started to migrate lock-on specific stuff to lock-on. The terminology change is highly necessary for other parts of Players code for example.

**Review by krm01 — APPROVED** [review]

**Pull request merged**
