### PR TITLE
Update asm_processor and use static variables in En_Torch2

### PR DESCRIPTION
**Pull request by Roman971**
With this new version of `asm_processor`, static symbols are now usable inside `GLOBAL_ASM`, so we can have static variables even if they are used inside non matchings.

Note that this wasn't tested extensively so it might not always work, but at least everything is OK right now, and there are no issues in the case of `En_Torch2`.

### CODE REVIEW

**Review by fig02 — APPROVED** [review]

**Comment by EllipticEllipsis** [comment]
Do we want to update the tutorial to reflect this? I suppose it doesn't really matter for WIP files.

**Comment by Roman971** [comment]
Updating the tutorial would probably be a good idea, if there are mentions of this limitation. I can look into it myself if needed, but if you want to make a PR with an update to the tutorial that's also fine to me.

**Comment by EllipticEllipsis** [comment]
I think https://github.com/zeldaret/oot/blob/master/docs/tutorial/data.md#data-first is the only explicit reference. The tutorial uses `extern` in the main example, so it's not an issue there.

**Comment by Roman971** [comment]
@EllipticEllipsis I think I updated the tutorial accordingly, let me know if this is what you had in mind

**Comment by EllipticEllipsis** [comment]
Yes, if you're satisfied that it'll work in general, this looks fine to me.

**Review by EllipticEllipsis — APPROVED** [review]

**Pull request merged**
