### PR TITLE
a number of small tweaks and improvements

### PR DESCRIPTION
**Pull request by playerskel**
A start to my contributions. Figured I'd just start somewhere. Happy to process feedback to something that can be merged.

### CODE REVIEW

**Review by AngheloAlf — COMMENTED** [review]
Hi. Welcome and thanks for your contribution.
I took a general look, and this PR looks a bit weird.
First, PRs this big should give a summary of what they are changing and why.
Second, I see you removed every trace of NON_MATCHING in the toolings of the repo, but currently there are no plans for removing any of those because those will be very helpful in the future multi version support.
Third, we don't use `clang-format off` unless it is required for matching code (yeah, the compiler is sensitive to formatting... it is fun... :slightly_smiling_face: )
Fourth, many of the changes feels more like those are the result of running some kind of automated tool on the whole repo, which we don't really do besides clang-format.

There are probably more stuff, but I didn't dig too much in the 599 files you changed.

For changes this big we usually discuss them first in the discord server. If you are not there, I suggest you to join so you can join the discussions with everybody else

**Review by Dragorn421 — COMMENTED** [review]
EDIT:

Thank you for your contribution! Many changes here look interesting

However this is way too big to review 😅 

-------

Some of this stuff others said already

#### Stuff that should just be dropped unfortunately
`NON_MATCHING` should stay
changes to `asm/` are covered by #865
all audio stuff (including `code_800EC960.c`, `code_800F9280.c`) is best left to engineer and simon, to avoid creating merge conflicts for them
`if (sword == PLAYER_SHIELD_MIRROR) {` is handled in #1098

#### Please split the rest
Please split the rest into several PRs, this is too much to review and discuss efficiently.
Suggestion on how to split things in 4 parts:
- memset/memmove renames
- whitespace, markdown and typo fixing
- other misc light documentation (`gDmaVerbose`, `ITEM00_NONE`, `GameInfo_Init`)
- moving actor flags from `#define FLAGS` to actor init vars

#### Other remarks
`// clang-format off`/on should be avoided, we like to use clang-format-11

**Comment by fig02** [comment]
heavily agreed on the above. Theres more specific things to talk about at a glance, but this PR is far too large to be able to effectively review it.

Not trying to pile on, just heavily encouraging pring in smaller doses so your changes can be effectively considered.
Dont worry about "spamming" like you mentioned in discord, more PRs is better than trying to manage one large pr for months (both for your sake, and reviewers).

And as mentioned already, try to talk about some larger scale changes in the discord before doing them, to see if people agree

**Comment by playerskel** [comment]
Thanks for the useful feedback on this, interesting, PR. Will do as suggested.

**Pull request closed without merging**
