### PR TITLE
Checksums for ntsc 1.2 JP and US, accept both as baserom for ntsc-1.2

### PR DESCRIPTION
**Pull request by Dragorn421**
This PR introduces the concept that several baseroms can be used for a version, like here either ntsc-1.2-jp or ntsc-1.2-us can be used as baserom for our "composite version" ntsc-1.2.

The changes are pretty straightforward

### CODE REVIEW

**Comment by cadmic** [comment]
I don't really think we need to check the checksum for the US version, it's not like we'll forget how to build it. I suggest we patch the region byte to J during setup like we do for the Debug ROM and call it a day (that already has the concept that "several baseroms can be used for a version" and we'll eventually need to make that clear in the README too).

In other words I think it's simpler if ntsc-1.2 always means the J version rather than a "composite version"

**Comment by Dragorn421** [comment]
Is there something preventing us from renaming baseroms/ntsc-1.2 to baseroms/ntsc-1.2-jp ?

**Comment by cadmic** [comment]
Not really other than it feels like unnecessary typing. I probably feel more strongly about that than the 2 checksums tbh

**Comment by cadmic** [comment]
I also don't really care which of JP or US is the default, I used JP because Nintendo is Japanese and because it's much more common in speedrunning. Maybe it could be friendlier to modders if we declared ntsc-1.2 to be the US version?

**Comment by cadmic** [comment]
(sorry for the spam) That might jive better with the 0.9 prerelease being a US ROM, presumably there's also a JP version but we don't have it. (Although maybe it was originally JP and the dumper changed the region byte?)

**Comment by Dragorn421** [comment]
I would like it to be somehow documented which rom is expected/built. The simplest would be to just call the version `ntsc-1.2-jp` if the "composite version" isn't an option

**Comment by cadmic** [comment]
What about something like this in the README?

Screenshot 2024-08-11 at 2 20 22 PM

https://github.com/cadmic/oot/blob/39158023877291675d7213b319781a9afb096b08/README.md

**Comment by Dragorn421** [comment]
I would like we pick between either
- distinguish all versions, so have baseroms/ntsc-1.2-{jp,us}
- `ntsc-1.2` really is/can be either jp/us, and not just an alias for only one

**Comment by cadmic** [comment]
Alright, of the two I'd prefer the latter (this PR I guess). Could you explain your reasoning though? I still don't really see what's wrong with only supporting one of JP/US, and having the other be a trivial "mod". That would work fine for both reverse engineering the game and modding, which I think are the two main uses of this repo

**Review by cadmic — APPROVED** [review]

**Review by fig02 — APPROVED** [review]
fwiw i agree with dragorns reasonings and this approach

**Pull request merged**
