### PR TITLE
Run fix_bss.py in Jenkins and generate a patch

### PR DESCRIPTION
**Pull request by cadmic**
Now, formatting and BSS ordering issues will not abort the build (although they will still show up as failures in the build overview, stage results, and pipeline steps). Instead, at the end there will be some output like this:

```
+ tools/generate_patch_from_jenkins.sh
Jenkins made some fixes to your PR. To apply these changes to your working directory,
copy and run the following command (triple-click to select the entire line):

echo -n ZGlmZiAtLWdpdCBhL3NyYy9jb2RlL3N5c19tYXRoM2QuYyBiL3NyYy9jb2RlL3N5c19tYXRoM2QuYwppbmRleCBmMTkxYjdjYjkuLjFhMzVlNjI1YSAxMDA2NDQKLS0tIGEvc3JjL2NvZGUvc3lzX21hdGgzZC5jCisrKyBiL3NyYy9jb2RlL3N5c19tYXRoM2QuYwpAQCAtNSw3ICs1LDcgQEAKICNpbmNsdWRlICJtYWNyb3MuaCIKICNpbmNsdWRlICJzeXNfbWF0aDNkLmgiCiAKLSNwcmFnbWEgaW5jcmVtZW50X2Jsb2NrX251bWJlciAiZ2MtZXU6MTA1IGdjLWV1LW1xOjEwNSBnYy1qcDowIGdjLWpwLWNlOjEwNSBnYy1qcC1tcToxMDUgZ2MtdXM6MCBnYy11cy1tcToxMDUiCisjcHJhZ21hIGluY3JlbWVudF9ibG9ja19udW1iZXIgImdjLWV1OjEwNSBnYy1ldS1tcToxMDUgZ2MtanA6MTA1IGdjLWpwLWNlOjEwNSBnYy1qcC1tcToxMDUgZ2MtdXM6MCBnYy11cy1tcToxMDUiCiAKIHMzMiBNYXRoM0RfTGluZVZzTGluZUNsb3Nlc3RUd29Qb2ludHMoVmVjM2YqIGxpbmVBUG9pbnRBLCBWZWMzZiogbGluZUFQb2ludEIsIFZlYzNmKiBsaW5lQlBvaW50QSwgVmVjM2YqIGxpbmVCUG9pbnRCLAogICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICBWZWMzZiogbGluZUFDbG9zZXN0VG9CLCBWZWMzZiogbGluZUJDbG9zZXN0VG9BKTsKQEAgLTIzLDcgKzIzLDcgQEAgczMyIE1hdGgzRF9TcGhDdWJlVnNUcmlDdWJlKFZlYzNmKiB2MCwgVmVjM2YqIHYxLCBWZWMzZiogdjIsIFZlYzNmKiBjZW50ZXIsIGYzMgogICovCiBzMzIgTWF0aDNEX1BsYW5lVnNMaW5lU2VnQ2xvc2VzdFBvaW50KGYzMiBwbGFuZUFBLCBmMzIgcGxhbmVBQiwgZjMyIHBsYW5lQUMsIGYzMiBwbGFuZUFEaXN0LCBmMzIgcGxhbmVCQSwgZjMyIHBsYW5lQkIsCiAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIGYzMiBwbGFuZUJDLCBmMzIgcGxhbmVCRGlzdCwgVmVjM2YqIGxpbmVQb2ludEEsIFZlYzNmKiBsaW5lUG9pbnRCLAotICAgICAgICAgICAgIFZlYzNmKiBjbG9zZXN0UG9pbnQpIHsKKyAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgVmVjM2YqIGNsb3Nlc3RQb2ludCkgewogICAgIHN0YXRpYyBJbmZpbml0ZUxpbmUgcGxhbmVJbnRlcnNlY3RMaW5lOwogICAgIHN0YXRpYyBMaW5lZiBwbGFuZUludGVyc2VjdFNlZzsKIAo= | base64 -d | git apply -
```

Running this command will apply the fixes to your working directory. Should it also try to commit them as well (say with `git commit -a -m 'Apply fixes from Jenkins'`)?

Here's a full build as an example: https://jenkins.deco.mp/job/OOT/job/PR-2165/16/

Note the build will still be aborted if `make setup` fails, or if `fix_bss.py` fails, since those indicate something is more wrong than formatting or bss.

Also, Jenkins does not like the colored output from fix_bss.py, so I made some changes to turn it off if stdout is not a TTY (other Python ANSI color libraries apparently support this easily but not I couldn't get colorama to do it).

### CODE REVIEW

**Review by fig02 — APPROVED** [review]
very cool and very helpful
is jenkins committing/writing to your branch for you a thing? would be even more convenient, but idk if we want to go down that road (if it exists)

**Comment by cadmic** [comment]
Hmm I haven't really thought about how that would work, I think we'd need to set up a new github account and every contributor would need to give that account push access to their local fork (or push access to zeldaret/oot, but I don't think that's a good idea because implicitly everybody who runs a Jenkins agent would also be able to push as that user). It might be annoying too though, it could push at an unpredictable time as you're making local changes to your PR

**Comment by fig02** [comment]
yeah good points

**Comment by cadmic** [comment]
Actually, giving the account push access to zeldaret/oot is probably not bad if the main branch is protected, and we could give different people different private keys so they could be revoked individually or something. Still seems kinda tricky though

**Review by Dragorn421 — APPROVED** [review]

**Pull request merged**
